<?php
/**
 * Customers Who Purchased
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Upsell
 * @version      2.1.2
 * @license:     cYj8qLquCcta0g5aoIvU1NU680GWIdT5W8W05jfDJH
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
/* @var $this Aitoc_Aitsys_Block_Notification */
?>
<div class="fieldset">
  <div class="news">
      <?php foreach ($this->getNews() as $item) { ?>
          <dl class="item">
            <dt>
                <?php if (isset($item['title']) && $item['title']) { ?>
                    <h2><?php echo $item['title']?></h2>
                <?php } ?>
            </dt>
            <dd>
              <?php echo $item['content']?>
            </dd>
          </dl>
      <?php } ?>
  </div>
</div>