<div class="category-wapper">
    <div class="recipes-search-box">
        <form action="<?php echo $this->getUrl('recipe/index/search') ?>" method="get" id="recipes-search-form">
            <fieldset>
                <div class="columns">
                    <div class="c_l">
                        <div class="label-box">
                            <label for="recipes-search" ><?php echo $this->__('Search Recipes:') ?></label>
                        </div>
                    </div>
                    <div class="c_c">
                        <div class="input-box">
                            <input type="text" id="searchrecipe" name="search" title="<?php echo $this->__('Name of the recipe') ?>" placeholder="<?php echo $this->__('Name of the recipe...') ?>" class="input-text required-entry">
                            <span class="fa fa-search"></span>
                        </div>
                    </div>
                    <div class="c_r">
                        <div class="submit-box">
                            <button type="submit" title="Search recipes"><span><?php echo $this->__('Search Recipes') ?></span></button>
                        </div>
                        <div class="advanced-box">
                            <a href="<?php echo $this->getUrl('recipe/index/advancesearch') ?>"><?php echo $this->__('Advanced Search') ?></a>
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <script type="text/javascript">
    //<![CDATA[
        var recipeSearchrFormDetail = new VarienForm('recipes-search-form');
    //]]>;
    </script>
</div>
