<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('recipie_banner')->toHtml(); ?>

<div class="category-wapper">
    <div class="productcarousel3 block productcarousel" id="module80731414420324">
        <div class="block-title">
            <?php if($this->getSearchStr()): ?>
                <h4><?php echo $this->__("Search results for ' %s '",$this->getSearchStr());?></h4>
            <?php else: ?>
                <h4><?php echo $this->__("Search results");?></h4>
            <?php endif ?>
            <div class="pretext"></div>
        </div>
        <div class="block-content">
            <div class="box-products carousel slide" id="productcarousel380731414420324">
                <?php /* ?>
                <div class="carousel-controls">
                    <a class="carousel-control left fa fa-angle-double-left" href="#productcarousel380731414420324" data-slide="prev"></a>
                    <a class="carousel-control right fa fa-angle-double-right" href="#productcarousel380731414420324" data-slide="next"></a>
                </div>
                <?php */ ?>
                 <?php echo $this->getChildHtml('recipe_list'); ?>  
             </div>
        </div>
    </div>
</div>    
<?php //echo $this->getChildHtml('recipie_inspire_banner'); ?>  
