<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Create New Quotation')?></h3></td>
            <td class="a-right">
                <button onclick="document.location.href='<?php echo $this->getBackUrl()?>'" class="scalable back" type="button"><span><?php echo $this->__('Back')?></span></button>
                <button onclick="editForm.submit();" class="scalable save" type="button"><span><?php echo $this->__('Save')?></span></button>
            </td>
        </tr>
    </table>
</div>
<form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/create')?>">
<input id="form_key" name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<div class="entry-edit">
    
    <input type="hidden" name="myform[customer_id]" value="<?php echo $this->getCustomer()->getId(); ?>" />
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?php echo $this->__('Customer')?> </td>
                    <td class="input-ele"><?php echo  $this->getCustomer()->getName(); ?></td>
                </tr>
                <tr>
                    <td class="label"><?php echo $this->__('Caption')?> <span class="required">*</span></td>
                    <td class="input-ele"><input style="width:400px;" class="input-text required-entry" id="myform[caption]" name="myform[caption]" value="" /></td>
                </tr>
            </table>
        </fieldset>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>

</form>
