<div class="content-header">
    <h3 class="icon-head head-Adminhtml"><?php echo $this->__('Select customer') ?></h3>
</div>
<div>
    <fieldset>
        <div align="right">
            <?php if ($this->canCreateCustomer()): ?>
                <button onclick="document.location.href='<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/customer/new'); ?>'" class="scalable add" type="button"><span><?php echo $this->__('Create new customer') ?></span></button>
            <?php endif; ?>
        </div>
        <?php echo $this->getGridParentHtml(); ?>
    </fieldset>
</div>


