  <div class="content-header">
    <table cellspacing="0">
        <tbody><tr>
            <td style="width: 50%;"><h3 class="icon-head head-notification">StoreYa</h3></td>
            <td class="form-buttons"></td>
        </tr>
    </tbody></table>
</div>
<div>
                
        <div id="notificationGrid">
        
<div id="notificationGrid_massaction">
<table cellspacing="0" cellpadding="0" class="massaction">
<tbody><tr>
    <td>Create Api User&nbsp;</td>
    <td>
        <div class="right">
            <div class="entry-edit">
                <form method="post" id="notificationGrid_massaction-form" action="">
                    <div><input type="hidden" value="QPSXxWavarNAvn07" name="form_key"></div>
                    <fieldset>
                        
                        <span class="field-row">
                            <button style="" onclick="setLocation('{{@@url@@}}')" class="scalable" type="button" id="btn-create-storeya"><span>Create API</span></button>                        </span>
                    </fieldset>
                </form>
            </div>

            
        </div>
    </td>
</tr>
</tbody></table>
</div>
<div class="grid">
    <div class="hor-scroll">
    <table cellspacing="0" id="notificationGrid_table" class="data">
                <col width="20" class="a-center">
                <col width="60">
                <col width="150">
                <col>
                <col width="250">
               <thead>
               <!--
				<tr class="headings">
						<th><span class="nobr">&nbsp;</span></th>
						<th><span class="nobr"><a class="not-sort" title="asc" name="severity" href="#"><span class="sort-title">Severity</span></a></span></th>
						<th><span class="nobr"><a class="sort-arrow-desc" title="asc" name="date_added" href="#"><span class="sort-title">Date Added</span></a></span></th>
						<th><span class="nobr"><a class="not-sort" title="asc" name="title" href="#"><span class="sort-title">Message</span></a></span></th>
						<th class=" no-link last"><span class="nobr">Actions</span></th>
					</tr>
					-->
			   </thead>
                
        <tbody id="">
                    <tr class="even" id="">
                <td colspan="5" class="empty-text a-center">{{@@msg@@}}</td>
            </tr>
                </tbody>

    </table>
    </div>
</div>
</div>
</div>
