<?php
/******************************************************
 * @package Ves Megamenu module for Magento 1.4.x.x and Magento 1.7.x.x
 * @version 1.0.0.1
 * @author http://landofcoder.com
 * @copyright	Copyright (C) December 2010 LandOfCoder.com <@emai:landofcoder@gmail.com>.All rights reserved.
 * @license		GNU General Public License version 2
*******************************************************/
$title = $this->getConfig("title");

$show = false;
$category = Mage::registry('current_category');
$is_homepage = Mage::getBlockSingleton('page/html_header')->getIsHomePage();

if($category) {
   if(($category->getParentId() != $category->getId() && $category->getParentId() != 2)) {
      $show = true;
   }
}
if($is_homepage) {
   $show = true;
}

if($show == true) {
?>
<div id="ves-verticalmenu" class="block ves-verticalmenu highlighted hidden-xs hidden-sm">
	<?php if($title) { ?>
	<div class="block-title">
		<span class="icon-menu">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</span>
		<h4><?php echo $title; ?></h4>	

		<em class="shapes right"></em>	
		<em class="line"></em>
	</div>
	<?php } ?>
	<div class="block-content">
		<div class="navbar navbar-inverse">
			<div id="verticalmenu" class="verticalmenu" role="navigation">
				<div class="navbar">
				<a href="#" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			     </a>
				<div class="collapse navbar-collapse navbar-ex1-collapse">
				<?php echo $menuHtml; ?>
				 </div></div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery(window).ready( function(){

	/*  Fix First Click Menu */
	jQuery(document.body).on('click', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
	jQuery(document.body).on('dblclick', '#verticalmenu [data-toggle="dropdown"]' ,function(event){
		event.stopImmediatePropagation();
		jQuery(this).parent().show();
		if(!jQuery(this).parent().hasClass('open') && this.href && this.href != '#'){
			window.location.href = this.href;
		}

	});
});
</script>
<?php
}
?>
