<?php
/**
 * Customers Who Purchased
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Upsell
 * @version      2.1.2
 * @license:     cYj8qLquCcta0g5aoIvU1NU680GWIdT5W8W05jfDJH
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
/**
 * @var $this Aitoc_Aitsys_Block_Rewriter_Notifications
 */ 
if ($this->isShow()) { ?>
<div class="notification-global">
    <strong><?php echo $this->helper('aitsys')->__('Class Rewrites cache is disabled.') ?></strong>
    <?php echo $this->helper('aitsys')->__('It is strongly recommended to turn it on! Do not turn it off except for development purposes!') ?>
    <?php echo $this->helper('aitsys')->__('Click here to go to <a href="%s">Cache Management</a> and enable Class Rewrites cache.', $this->getManageUrl());?>
</div>
<?php } ?>