<?php /***********(start)them static structure****************** ?>
<section id="ves-promotion" class="ves-promotion">
    <div class="productcarousel1 block productcarousel" id="module11815270491411642138">
        <div class="block-title">
            <h4>Recipes</h4>
            <div class="pretext"></div>
        </div>
        <div class="block-content">
            <div class="box-products carousel slide" id="recipescarousel">
                <div class="carousel-controls">
                    <a class="carousel-control left fa fa-angle-double-left" href="#recipescarousel"   data-slide="prev"></a>
                    <a class="carousel-control right fa fa fa-angle-double-right" href="#recipescarousel"  data-slide="next"></a>
                </div>
                <div class="carousel-inner">        
                    <div class="item first active product-grid no-margin">

                            <div class="row products-grid">
                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item first">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="Lorem ipsum dolor sit amet" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/8/_/8.jpg" width="300" height="300" alt="Lorem ipsum dolor sit amet" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="Lorem ipsum dolor sit amet">Lorem ipsum dolor sit amet</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:80%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/1/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="MHS-TS55 Bloggie Live Camcorder" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/5/_/5_2.jpg" width="300" height="300" alt="MHS-TS55 Bloggie Live Camcorder" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="MHS-TS55 Bloggie Live Camcorder">Lorem ipsum dolor sit amet2</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:60%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/3/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="HC-X900M 3D Ready Full HD Camcorder" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/2/0/20.jpg" width="300" height="300" alt="HC-X900M 3D Ready Full HD Camcorder" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="HC-X900M 3D Ready Full HD Camcorder">Lorem ipsum dolor sit amet3</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:67%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/5/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item last">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="VIXIA HF M500 Full HD Camcorder" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/6/16_1.jpg" width="300" height="300" alt="VIXIA HF M500 Full HD Camcorder" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="VIXIA HF M500 Full HD Camcorder">Lorem ipsum dolor sit amet4</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:60%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/6/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>



                        <script type="text/javascript">
                             jQuery(document).ready(function() {
                                  jQuery(".ves-colorbox").colorbox({
                                             width: '60%', 
                                             height: '80%',
                                             overlayClose: true,
                                             opacity: 0.5,
                                             iframe: true, 
                                  });

                             });
                        </script>

                    </div> 
                    <div class="item last  product-grid no-margin">

                        <div class="row products-grid">


                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item first">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="EOS Rebel T4i Digital Camera" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/0/10.jpg" width="300" height="300" alt="EOS Rebel T4i Digital Camera" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="EOS Rebel T4i Digital Camera">Lorem ipsum dolor sit amet5</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:60%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/2/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="EOS Rebel T4i Digital Camera" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/3/13_2.jpg" width="300" height="300" alt="EOS Rebel T4i Digital Camera" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="EOS Rebel T4i Digital Camera">Lorem ipsum dolor sit amet6</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:67%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/7/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="EOS 5D Mark II Digital Camera" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/7/17_3.jpg" width="300" height="300" alt="EOS 5D Mark II Digital Camera" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="EOS 5D Mark II Digital Camera">Lorem ipsum dolor sit amet7</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:60%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/8/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>





                            <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item last">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="#" itemprop="url" title="D800 Digital SLR Camera" class="product-image"><img src="http://wingyip.staging5.newedge.co.uk/media/catalog/product/cache/1/small_image/300x300/9df78eab33525d08d6e5fb8d27136e95/1/9/19_4.jpg" width="300" height="300" alt="D800 Digital SLR Camera" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="#" title="D800 Digital SLR Camera">Lorem ipsum dolor sit amet8</a>
                                            </h2>
                                            <div class="rating">    <div class="ratings">
                                                    <div class="rating-box">
                                                        <div class="rating" style="width:67%"></div>
                                                    </div>
                                                    <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://wingyip.staging5.newedge.co.uk/index.php/review/product/list/id/9/'; return false;">1 Review(s)</a></span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>



                        <script type="text/javascript">
                             jQuery(document).ready(function() {
                                  jQuery(".ves-colorbox").colorbox({
                                             width: '60%', 
                                    height: '80%',
                                    overlayClose: true,
                                    opacity: 0.5,
                                    iframe: true,
                                });

                            });
                        </script>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery('#recipescarousel').carousel({interval: false, auto: false, pause: 'hover', cycle: true});
    </script>
</section>
<?php **********(end)them static structure*******************/ ?>

<?php $recipeCollection = $this->getCollection() ?>
<?php $count = $recipeCollection->count() ?>
<?php if(!$count): ?>
    <p class="note-msg"><?php echo $this->__('There are no recipes matching the selection.') ?></p>
<?php else: ?>
<section id="ves-promotion" class="ves-promotion">
    <div class="productcarousel1 block productcarousel" id="module11815270491411642138">
        <div class="block-title">
            <h4>Recipes</h4>
            <div class="pretext"></div>
        </div>
        <div class="block-content">
            <div class="box-products carousel slide" id="recipescarousel">
                <div class="carousel-controls">
                    <a class="carousel-control left fa fa-angle-double-left" href="#recipescarousel"   data-slide="prev"></a>
                    <a class="carousel-control right fa fa fa-angle-double-right" href="#recipescarousel"  data-slide="next"></a>
                </div>
                <div class="carousel-inner">
                    <?php $_collectionSize = $recipeCollection->count() ?>
                    <?php $_columnCount = 4; ?>
                    <?php $i=0; foreach ($recipeCollection as $_recipe): ?>
                        <?php if ($i++%$_columnCount==0): ?>
                        <div class="item product-grid no-margin <?php if($i==1):?>first active <?php endif; ?>">
                        <div class="row products-grid">
                        <?php endif ?>
                        <div class="col-xs-12 col-lg-3 col-sm-3 col-3 _item <?php if((($i-1)%$_columnCount)==0): ?> first<?php elseif(($i%$_columnCount)==0): ?> last<?php endif; ?>">
                                <div class="product-block" itemtype="http://schema.org/Product" itemscope>
                                    <div class="product-content">
                                        <div class="image ">
                                            <a href="<?php echo $this->getRecipeUrl($_recipe); ?>" itemprop="url" class="product-image" title="<?php echo $_recipe->getName(); ?>"><img src="<?php echo $this->helper('recipe')->resizeImage(300,300,$_recipe->getImage()); ?>" width="300" height="300" alt="<?php echo $_recipe->getName(); ?>" /></a>
                                        </div>
                                        <div class="product-info">
                                            <h2 class="product-name" itemprop="name"><a href="<?php echo $this->getRecipeUrl($_recipe); ?>" title="<?php echo $_recipe->getName(); ?>"><?php echo $_recipe->getName(); ?></a>
                                            </h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                    </div>
                    </div>
                    <?php endif ?>
                    <?php endforeach ?>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery('#recipescarousel').carousel({interval: false, auto: false, pause: 'hover', cycle: true});
    </script>
</section>
<?php endif; ?> 



<?php /* ?>
    <div class="category-products">
        <?php //echo $this->getChildHtml('pager'); ?> 
        <ol class="products-list" id="products-list">
            <?php $_iterator = 0?>
            <?php foreach($recipeCollection as $_recipe):?>    
                <li class="item<?php if( ++$_iterator == $count ): ?> last<?php endif; ?>">
                <a href="<?php echo $this->getRecipeUrl($_recipe); ?>" title="<?php echo $_recipe->getName(); ?>"><img src="<?php echo $this->helper('recipe')->resizeImage(135,135,$_recipe->getImage()); ?>" width="135" height="135" alt="<?php echo $_recipe->getName(); ?>" /></a>
                
                <div class="product-shop">
                    <div class="f-fix"> 
                        <a href="<?php echo $this->getRecipeUrl($_recipe); ?>" title="<?php echo $_recipe->getName(); ?>"><h2 class="product-name"><?php echo $_recipe->getName(); ?></h2></a>
                        <div class="desc std"><?php echo $_recipe->getDescription(); ?></div>
                    </div>
                </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
<?php */ ?>
