<?php $_helper = $this->helper('recipe'); ?>  
<?php $_recipe = $this->getRecipe(); ?>      

<div class="product-view product-recipe">
    <div class="product-essential row">
        <div class="product-shop col-xs-12">
            <div class="row">
                <div class="product-img-box col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <img src="<?php echo $_helper->resizeImage(380,380,$_recipe->getImage()) ?>" alt="<?php echo $_recipe->getName(); ?>" />
                <?php if($_recipe->getVideo()): ?>
                    <p>
                        <a class="fancybox-media" href="<?php echo $_recipe->getVideo() ?>?autoplay=1" rel="media-gallery"><?php echo $this->__("click here,"); ?></a>
                        <?php echo $this->__(" to play the video") ?>
                    </p>
                <?php endif; ?>
                </div>
                <div class="product-name col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <h1><?php echo $_recipe->getName() ?></h1>
                    <div class="short-description">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <div class="std"><?php echo $_recipe->getShortDescription() ?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="tabs-group product-collateral">
        <div id="tabs" class="htabs clearfix">
            <div class="tab-desc"><a href="#tab-description" class="description selected">Description</a></div>
            <div class="tab-desc"><a href="#tab-ingredients" class="ingredients selected">ingredients</a></div>
        </div>
        <div class="tab-content box-description" id="tab-description" style="display: block;">        
            <div>
                <?php echo $_recipe->getDescription() ?>        
            </div>
            <br class="clear clr">
        </div>
        <div class="tab-content box-ingredients" id="tab-ingredients" style="display: block;">        
            <div>
                <?php $ingredients = $this->getIngredients($_recipe); ?>
                <?php if($ingredients->count() > 0): ?>
                <div class="ingredients col-xs-12 col-md-4 col-sm-6">
                    <h4><?php echo $this->__('Ingredients') ?></h4>
                    <ul>
                    <?php foreach($ingredients as $_ingredient): ?>
                         <li><?php echo $_ingredient->getName() ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
                <?php endif ?>  
                
                <?php $cupboardIngredients = $this->getCupboardIngredients($_recipe); ?>
                <?php if($cupboardIngredients->count() > 0): ?>
                <div class="cupboard_ingredients col-xs-12 col-md-4 col-sm-6">
                    <h4><?php echo $this->__('Cupboard Ingredients') ?></h4>
                    <ul>
                    <?php foreach($cupboardIngredients as $_cupboard): ?>
                         <li><?php echo $_cupboard->getName() ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
                <?php endif ?>  
                
            </div>
            <br class="clear clr">
        </div>
    <div> 
    <div class="associated">
        <?php echo $this->getChildHtml("recipe_associated") ?>
    </div>  
</div>
<script type="text/javascript">

jQuery(document).ready(function() {  

    jQuery('.fancybox-media').fancybox({  
    'width'                : '75%',
    'height'            : '75%',
    'autoScale'         : false,
    'transitionIn'        : 'none',
    'transitionOut'        : 'none',
    'type'                : 'iframe'
    });
});
</script>




