<?php
/**
 * Wingyip_Realex extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Wingyip
 * @package    Wingyip_Realex
 
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    
    <?php $redirect = Mage::getModel('realex/redirect'); ?>
    
    <?php if($redirect->getConfigData('amexAccount')): ?>
     <ul id="payment_form_<?php echo $_code ?>" style="display:none">
     	<li>You will be redirected to the Realex website once you place your order.</li>
        <li>
           <input id="<?php echo $_code ?>_amex" value="amex" type="radio" name="payment[amex]" title="American Express" class="radio"  />
           <label for="<?php echo $_code ?>_amex">Pay with American Express</label><br />
           <input id="<?php echo $_code ?>_other" value="other" type="radio" name="payment[amex]" title="Other Credit Card" class="radio" checked="checked"  />
           <label for="<?php echo $_code ?>_other">Pay with Other Credit/Debit Card</label>
        </li>
    </ul>
    <?php else : ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to the Realex website when you place an order.') ?>
        </li>
    </ul>
    <?php endif; ?>
</fieldset>