<div class="entry-edit">

    <div class="content-header">
        <table cellspacing="0" class="grid-header">
            <tr>
                <td><h3><?php echo$this->__('Quotations') ?></h3></td>
                <td align="right">
                    <button type="button" class="scalable add" onClick="document.location.href ='<?php echo $this->getUrl('Quotation/Admin/SelectOrCreateCustomer') ?>'"><span><?php echo $this->__('New') ?></span></button>
                </td>
            </tr>
        </table>
    </div>

    <?php echo $this->getGridParentHtml() ?>

</div>