<?php
/******************************************************
 * @package Ves Verticalmenu module for Magento 1.9.0.1
 * @version 1.0
 * @author http://www.venustheme.com
 * @copyright   Copyright (C) Feb 2013 VenusTheme.com <@emai:venustheme@gmail.com>.All rights reserved.
 * @license     GNU General Public License version 2
*******************************************************/
$menu = $this->getVerticalmenu();
if( $menu ): 
$menu_image = $menu->getImage();
if($menu_image != ""){
    $menu_image = Mage::helper('ves_verticalmenu')->resizeImage($menu_image, 135, 135);
}
$module_row= 'ss';
$text_edit_menu = Mage::helper("ves_verticalmenu")->__("Edit: %s (ID:%s)");

$yesno = array(1 => Mage::helper('ves_verticalmenu')->__('Yes'),
                  0 => Mage::helper('ves_verticalmenu')->__('No'));

$submenutypes = array('menu'=>'Menu', 'html'=>'HTML','widget'=>'Widget');

$verticalmenutypes = $this->getMenuTypes();

$product_id = ($menu->getId() && $menu->getType() == 'product')?$menu->getItem():"";

$widgets = $this->getWidgets();

?>
<?php if( $menu->getVerticalmenuId() > 0 ) { ?>
<h3><?php echo sprintf($text_edit_menu, $menu->getTitle(), $menu->getVerticalmenuId());?></h3>
<?php } else { ?>
<h3><?php echo Mage::helper("ves_verticalmenu")->__("Create New Verticalmenu");?></h3>
<?php } ?>
<div>
<?php 
// echo '<pre>'.print_r( $menu_description,1 ); die;
?>
    <h4><?php Mage::helper("ves_verticalmenu")->__("Menu Information");?></h4>
    <table class="form">
      <tr>
        <td><?php echo Mage::helper("ves_verticalmenu")->__("Title");?></td>
        <td><input name="verticalmenu[title]" value="<?php echo $menu->getTitle();?>" size="50"/></td>
      </tr>
       <tr>
        <td><?php echo Mage::helper("ves_verticalmenu")->__("Description");?></td>
        <td>
            <textarea name="verticalmenu[description]" cols="5" style="width:400px" rows="10"><?php echo $menu->getDescription(); ?></textarea>
        </td>
      </tr>
    </table>
    <h4><?php Mage::helper("ves_verticalmenu")->__("Menu Type");?></h4>
    <input type="hidden" name="verticalmenu[item]" value="" />
    <table class="form">
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__("is Published");?></td>
                
            <td>
                <select type="list" name="verticalmenu[published]" >
                    <?php foreach( $yesno as $key => $val ){ ?>
                    <option value="<?php echo $key;?>" <?php if( $key==$menu->getPublished()){ ?> selected="selected"<?php } ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Type:');?></td>
                
            <td>
                <select name="verticalmenu[type]" id="verticalmenutype">
                    <?php foreach(  $verticalmenutypes as $mt => $val ){ ?>
                    <option value="<?php echo $mt; ?>" <?php if($mt == $menu->getType()) {?> selected="selected" <?php } ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr id="verticalmenutype-url" class="verticalmenutype">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('URL:');?></td>
            <td>
                <input type="text" name="verticalmenu[url]" value="<?php echo $menu->getUrl();?>" size="50"/>
            </td>
        </tr>
        <tr id="verticalmenutype-category" class="verticalmenutype">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Category');?></td>
            <td> 
               <?php echo $this->getItemHtml('category', (!$menu->getId() || $menu->getType() != 'category')); ?>
                <i><?php Mage::helper("ves_verticalmenu")->__('Select a category');?></i>
            </td>
        </tr>
        <tr id="verticalmenutype-product" class="verticalmenutype">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Product');?></td>
            <td>
                <input type="text" name="verticalmenu[product]" value="<?php echo $product_id;?>" size="50"/>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('Type Product Id');?></i>
            </td>
        </tr>
        <tr id="verticalmenutype-cms_page" class="verticalmenutype">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Cms Page');?></td>
            <td>
                <?php echo $this->getItemHtml('cms_page', (!$menu->getId() || $menu->getType() != 'cms_page')); ?>
            </td>
        </tr>
        <tr id="verticalmenutype-html" class="verticalmenutype">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('HTML');?></td>
            <td>
                <?php echo Mage::helper('ves_verticalmenu')->getElementEditor('verticalmenu-content_text-1','verticalmenu[content_text]', $menu->getContentText()); ?>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('If menu content is HTML so all submenu of this menu will not be showed');?></i>
            </td>
        </tr>
    </table>    
    <h4>Menu Params</h4>      
     <table class="form">
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Parent ID: ');?></td>
                
            <td>
                <?php echo Mage::helper('ves_verticalmenu')->getElementMenus('verticalmenu-parentid','verticalmenu[parent_id]', $menu->getParentId()); ?>
            </td>
        </tr>
         <tr>
              <td><?php echo Mage::helper("ves_verticalmenu")->__('Image: ');?></td>
              <td valign="top">
                <div class="image">
                    <img src="<?php echo $menu_image; ?>" style="width:135px;height:135px" alt="" id="thumb">
                    <input name="verticalmenu[image]" value="<?php echo $menu->getImage(); ?>" id="image" type="hidden">
                    <br>
                    <input type="file" name="image" value=""/>
                    <br/><br/>
                    <input type="checkbox" name="image[delete]" id="image_delete" value="1"/> <label for="image_delete"><?php echo Mage::helper("ves_verticalmenu")->__('Delete Image ');?></label>
                </div></td>
            </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Menu Class:');?></td>
                
            <td>
                <input type="text" name="verticalmenu[menu_class]" value="<?php echo $menu['menu_class']?>"/>
                
            </td>
        </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Position:');?></td>
                
            <td>
                <input type="text" name="verticalmenu[position]" value="<?php echo isset($menu['position'])?$menu['position']:0; ?>"/>
                
            </td>
        </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Show Title:');?></td>
                
            <td>
                <select type="list" name="verticalmenu[show_title]" >
                    <?php foreach( $yesno as $key => $val ){ ?>
                    <option value="<?php echo $key;?>" <?php if( $key==$menu['show_title']){ ?> selected="selected"<?php } ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Is Group:');?></td>
                
            <td>
                <select type="list" name="verticalmenu[is_group]" value="">
                    <?php foreach( $yesno as $key => $val ){ ?>
                    <option value="<?php echo $key;?>" <?php if( $key==$menu['is_group']){ ?> selected="selected"<?php } ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('Set Group to allow All Submenu Items showing in same level of parent menu without hovering on parent to show them');?></i>
            </td>
        </tr>
        <tr style="display:none">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('entry_iscontent');?></td>
            <td>
                <select type="list" name="verticalmenu[is_content]">
                    <?php foreach( $yesno as $key => $val ){ ?>
                    <option value="<?php echo $key;?>" <?php if( $key==$menu['is_content']){ ?> selected="selected"<?php } ?>><?php echo $val; ?></option>
                    <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo Mage::helper("ves_verticalmenu")->__("Width Of Submenu Wrapper:");?>
            </td>
                
            <td>
                <input type="text" name="verticalmenu[width]" value="<?php echo $menu['width']?>"/>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('Input numeric value width of submenu wrapper to show more columns. For example: 780 on the frontend it will be 780px.');?></i>
            </td>
        </tr>
        <tr>
            <td>
                <?php echo Mage::helper("ves_verticalmenu")->__("Columns:");?>
            </td>
                
            <td>
                <input type="text" name="verticalmenu[colums]" value="<?php echo $menu['colums']?>"/>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('Submenu Items will be splited and showed in X column(s)');?></i>
            </td>
        </tr>

        <tr>
            <td>
            <?php echo Mage::helper("ves_verticalmenu")->__("Detail Columns Width");?>  
            </td>
                
            <td>
                <textarea type="text" name="verticalmenu[submenu_colum_width]" rows="5" style="width:400px"><?php echo $menu['submenu_colum_width']?></textarea>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('Enter detail width of each subcols in values 1->12.
Example: col1=3 col3=5');?></i>
            </td>
        </tr>
        <tr>
            <td><?php echo Mage::helper("ves_verticalmenu")->__("Sub Menu Type");?></td>
            <td>
                <?php //echo '<pre>'.print_r( $menu,1 ); die ;?>
                <select name="verticalmenu[type_submenu]" id="verticalmenu-type_submenu">
                    <?php foreach( $submenutypes as $stype => $text ) { ?>
                    <option value="<?php echo $stype;?>" <?php if($stype==$menu['type_submenu']) { ?> selected="selected"<?php } ?>><?php echo $text;?></option>
                    <?php } ?>
                </select>
                <i><?php echo Mage::helper("ves_verticalmenu")->__('If the type is Menu, so submenus of this will be showed');?></i>
            </td>
        </tr>
        <tr class="type_submenu" id="type_submenu-html" style="display:none;">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Submenu Content:');?></td>
            <td>
                <?php echo Mage::helper('ves_verticalmenu')->getElementEditor('verticalmenu-submenu_content-1','verticalmenu[submenu_content]', $menu->getSubmenuContent()); ?>
            
            </td>
        <tr>

        <tr class="type_submenu" id="type_submenu-widget" style="display:none;">
            <td><?php echo Mage::helper("ves_verticalmenu")->__('Widget Id:');?></td>
            <td>
                 <?php if( $widgets->count() > 0 )  { ?>
                 <select name="verticalmenu[widget_id]">
                    <?php foreach( $widgets as $w => $t ) { ?>
                    <option <?php if($t->getId() == $menu['widget_id']) { ?> selected="selected" <?php } ?>value="<?php echo $t->getId(); ?>"><?php echo $t->getName(); ?></option>
                    <?php } ?>
                 </select>
                 <?php } ?>
            </td>
        <tr>

    </table>
    <input type="hidden" name="verticalmenu[verticalmenu_id]" value="<?php echo $menu['verticalmenu_id']?>"/>
</div>
<?php endif; ?>

<script type="text/javascript"> 
jQuery("#type_submenu-"+jQuery("#verticalmenu-type_submenu").val()).show();
jQuery("#verticalmenu-type_submenu").change( function(){
    jQuery(".type_submenu").hide();
    jQuery("#type_submenu-"+jQuery(this).val()).show();
} );

   jQuery(".verticalmenutype").hide();
   jQuery("#verticalmenutype-"+ jQuery("#verticalmenutype").val()).show();
   jQuery("#verticalmenutype").change( function(){
        jQuery(".verticalmenutype").hide();
        jQuery("#verticalmenutype-"+jQuery(this).val()).show();
   } );
   
   

jQuery("#verticalmenu-information").change( function(){ 
    jQuery('input[name=\'verticalmenu[item]\']').val(jQuery(this).val());
} );


  
</script>