<?php $_helper = $this->helper('recipe'); ?>  
<?php $_recipe = $this->getRecipe(); ?>    

<script type="text/javascript">// <![CDATA[
 jQuery(function() {
        jQuery('#bookmarkme').click(function() {
            if (window.sidebar) { // Mozilla Firefox Bookmark
                window.sidebar.addPanel(document.title,window.location.href,'');
            } else if(window.external && ('AddFavorite' in window.external)) { // IE Favorite
                window.external.AddFavorite(location.href,document.title); 
                return false;
            } else if(window.opera && window.print) { // Opera Hotlist
                this.title=document.title;
                return true;
            } else { // webkit - safari/chrome
                alert('Press ' + (navigator.userAgent.toLowerCase().indexOf('mac') != - 1 ? 'Command/Cmd' : 'CTRL') + ' + D to bookmark this page.');
                return false;
            }
        });
    });
// ]]></script>
<?php /* ?><p></p><?php */ ?>

<div class="add-to-box">
    <a id="bookmarkme" class="button btn-cart" title="<?php echo $this->getLayout()->getBlock('head')->getTitle(); ?>" href="#" rel="sidebar"><i class="fa fa-heart"></i><span><?php echo $this->__('Add to favorites') ?></span></a>
    
</div>
