<?php
/**
 * SF9_Realex extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   SF9
 * @package    SF9_Realex
 * @copyright  Copyright (c) 2011 StudioForty9
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
	<input type="hidden" name="currency" id="currency" value="<?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode(); ?>" />

    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display: none;">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-amex-currency validate-maestro-currency">
                    <option value=""><?php echo $this->__('-- Please Select --'); ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_owner"><?php echo $this->__('Name as it appears on Credit Card') ?> <span class="required">*</span></label><br />
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
            </div>
        </li>
        <li id="realex-cc-number-wrapper">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label><br />
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>
     <?php if($this->hasVerification()): ?>
        <li id="realex-cvv-wrapper">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('CVV') ?> <span class="required">*</span></label>                &nbsp;
                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
<br />
                <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text validate-realex-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="" /></div>
            </div>
        </li>
        <?php endif; ?>
        
        <li id="realex-expiration-wrapper">
            <div class="input-box">
                <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br />
                <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry validate-realex-cc-exp">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </div>
                <div class="v-fix" style="padding-left:5px;">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </div>
            </div>
        </li>

       
        <?php if(in_array('Switch/Solo', $this->getCcAvailableTypes())): ?>
         <li id="realex-issue-number-wrapper" style="display:none;">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_ss_issue"><?php echo $this->__('Issue Number') ?></label><br />
                <div class="v-fix"><input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text" id="<?php echo $_code ?>_cc_ss_issue" name="payment[cc_ss_issue]" style="width:3em;" value="" /></div>
                &nbsp;
                only required for Switch/Solo cards
            </div>
        </li>
        <li id="realex-start-date-wrapper" style="display:none;">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_ss_start_month"><?php echo $this->__('Start Date') ?></label><br />
                <div class="v-fix">
                <select id="<?php echo $_code ?>_cc_ss_start_month" style="width:140px;" name="payment[cc_ss_start_month]" class="validate-cc-start">
                <?php $_ccStartMonth = $this->getInfoData('cc_ss_start_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                </div>
                <div class="v-fix" style="padding-left:5px;">
                <?php $_ccStartYear = $this->getInfoData('cc_ss_start_year') ?>
                <select id="<?php echo $_code ?>_cc_ss_start_year" style="width:103px;" name="payment[cc_ss_start_year]">
                <?php foreach ($this->getCcStartYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                only required for Switch/Solo cards
                </div>
            </div>
        </li>
        

 <?php endif; ?>
   
    </ul>
</fieldset>

<script type="text/javascript">

Event.observe('realex_cc_type', 'change', function(){
    if($('realex_cc_type').getValue() == 'LA'){
        $('realex-cvv-wrapper').hide();
    }else{
        $('realex-cvv-wrapper').show();
    }

    if($('realex_cc_type').getValue() == 'SS'){
        $('realex-issue-number-wrapper').show();
        $('realex-start-date-wrapper').show();
    }else{
        $('realex-issue-number-wrapper').hide();
        $('realex-start-date-wrapper').hide();
    }
});

Validation.creditCartTypes.unset('SM');
Validation.creditCartTypes  = Validation.creditCartTypes.merge({ 'LA': [new RegExp('^(6304|6709|6706|6771)[0-9]{12,15}$'), true, true] });
Validation.creditCartTypes  = Validation.creditCartTypes.merge({ 'EL': [new RegExp('^4[0-9]{12}([0-9]{3})?$'), new RegExp('^[0-9]{3}$'), true] });

Validation.addAllThese([
    ['validate-realex-cc-cvn', 'Please enter a valid credit card verification number.', function(v, elm) {
        		var ccTypeContainer = $('realex_cc_cid' + '_cc_type');
                if (!ccTypeContainer) {
                    return true;
                }
                var ccType = ccTypeContainer.value;

				if(ccType == 'LA'){
					return true;
				}
				
                if (typeof Validation.creditCartTypes.get(ccType) == 'undefined') {
                    return false;
                }

                var re = Validation.creditCartTypes.get(ccType)[1];

                return v.match(re);
     }],
   ['validate-realex-cc-exp', 'Incorrect credit card expiration date', function(v, elm) {
            var ccExpYear    = $('realex_expiration_yr').value;
            var currentTime  = new Date();
            var currentMonth = currentTime.getMonth() + 1;
            var currentYear  = currentTime.getFullYear();
            return !(v < currentMonth && ccExpYear == currentYear);

    }]
]);
</script>